// <auto-generated />
using System;
using InvetoryManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(InventoryManagementSystemContext))]
    partial class InventoryManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.IdentityModule.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.InventoryTransactionLog", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("Transaction_ID");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("Created_Date");

                    b.Property<int>("FromStoreId")
                        .HasColumnType("int")
                        .HasColumnName("From_Store_ID");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Performed_By");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("Reference_ID");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Reference_Type");

                    b.Property<int>("SerialId")
                        .HasColumnType("int")
                        .HasColumnName("Serial_ID");

                    b.Property<int>("ToStoreId")
                        .HasColumnType("int")
                        .HasColumnName("To_Store_ID");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("Transaction_Date");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Transaction_Type");

                    b.HasKey("TransactionId")
                        .HasName("PK__Inventor__9A8D5625FF51CF63");

                    b.HasIndex("FromStoreId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SerialId");

                    b.HasIndex("ToStoreId");

                    b.ToTable("Inventory_Transaction_Log", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrder", b =>
                {
                    b.Property<int>("IssueOrderId")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Order_ID");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Approved_By");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("Created_Date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("Issue_Date");

                    b.Property<int>("IssueOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Order_Number");

                    b.Property<string>("IssueType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Issue_Type");

                    b.Property<string>("IssuedTo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Issued_To");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("RequesterDepartment")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Requester_Department");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Requester_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("Store_ID");

                    b.Property<int?>("TotalValue")
                        .HasColumnType("int")
                        .HasColumnName("Total_Value");

                    b.HasKey("IssueOrderId")
                        .HasName("PK__Issue_Or__062A9D9E5964600C");

                    b.HasIndex("StoreId");

                    b.ToTable("Issue_Order", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrderDetail", b =>
                {
                    b.Property<int>("IssueDetailId")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Detail_ID");

                    b.Property<int>("IssueOrderId")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Order_ID");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<int?>("LineTotal")
                        .HasColumnType("int")
                        .HasColumnName("Line_Total");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("QuantityIssued")
                        .HasColumnType("int")
                        .HasColumnName("Quantity_Issued");

                    b.Property<int?>("UnitCost")
                        .HasColumnType("int")
                        .HasColumnName("Unit_Cost");

                    b.HasKey("IssueDetailId")
                        .HasName("PK__Issue_Or__16078A0F2217C939");

                    b.HasIndex("IssueOrderId");

                    b.HasIndex("ItemId");

                    b.ToTable("Issue_Order_Details", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrderSerial", b =>
                {
                    b.Property<int>("IssueSerialId")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Serial_ID");

                    b.Property<DateOnly?>("ExpectedReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("Expected_Return_Date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("Issue_Date");

                    b.Property<int>("IssueDetailId")
                        .HasColumnType("int")
                        .HasColumnName("Issue_Detail_ID");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReturnExpected")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Return_Expected");

                    b.Property<int>("SerialId")
                        .HasColumnType("int")
                        .HasColumnName("Serial_ID");

                    b.HasKey("IssueSerialId")
                        .HasName("PK__Issue_Or__9591F2AE1A57F3DC");

                    b.HasIndex("IssueDetailId");

                    b.HasIndex("SerialId");

                    b.ToTable("Issue_Order_Serials", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.ItemMaster", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Item_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("Create_Date");

                    b.Property<string>("IsSerialized")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Is_Serialized")
                        .IsFixedLength();

                    b.Property<string>("ItemCategory")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Item_Category");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int")
                        .HasColumnName("Item_Code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Item_Name");

                    b.Property<string>("ItemStatus")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Item_Status");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("Last_Modified_Date");

                    b.Property<int?>("MaximumStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("Maximum_Stock_Level");

                    b.Property<int?>("MinimumStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("Minimum_Stock_Level");

                    b.Property<string>("Specifications")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Specifications");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Unit_Of_Measure");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("Unit_Price");

                    b.HasKey("ItemId")
                        .HasName("PK__Item_Mas__3FB508748BF98A2F");

                    b.HasIndex(new[] { "ItemCode" }, "UQ__Item_Mas__F003364591D72A9D")
                        .IsUnique();

                    b.ToTable("Item_Master", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.ItemSerialNumber", b =>
                {
                    b.Property<int>("SerialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Serial_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialId"));

                    b.Property<int?>("CurrentStoreId")
                        .HasColumnType("int")
                        .HasColumnName("Current_Store_Id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_Id");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("Purchase_Date");

                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("Serial_Number")
                        .HasComputedColumnSql(" DEFAULT (NEXT VALUE FOR [increment])");

                    b.Property<string>("SerialStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Serial_Status");

                    b.Property<DateOnly?>("WarrantyExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("Warranty_Expiry_Date");

                    b.HasKey("SerialId")
                        .HasName("PK__Item_Ser__9F2EE2BD6C05F7C5");

                    b.HasIndex("CurrentStoreId");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "SerialNumber" }, "UQ__Item_Ser__96AF66AB920742D8")
                        .IsUnique();

                    b.ToTable("Item_Serial_Number", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.Models.Ccategory", b =>
                {
                    b.Property<int>("CcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CcategoryId"));

                    b.Property<string>("CcategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CcategoryId");

                    b.ToTable("Ccategories");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrder", b =>
                {
                    b.Property<int>("ReceivingOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Order_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceivingOrderId"));

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("Created_Date");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("Expected_Delivery_Date");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("Invoice_Date");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnType("int")
                        .HasColumnName("Invoice_Number");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PurchaseOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("Purchase_Order_Number");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Received_By");

                    b.Property<DateOnly?>("ReceivingDate")
                        .HasColumnType("date")
                        .HasColumnName("Receiving_Date");

                    b.Property<int?>("ReceivingOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Order_Number");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("Store_Id");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("int")
                        .HasColumnName("Total_Amount");

                    b.HasKey("ReceivingOrderId")
                        .HasName("PK__Receivin__5F665925CEC9FD58");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receiving_Order", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrderDetail", b =>
                {
                    b.Property<int>("ReceivingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Detail_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceivingDetailId"));

                    b.Property<int?>("BatchNumber")
                        .HasColumnType("int")
                        .HasColumnName("Batch_Number");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("Expiry_Date");

                    b.Property<string>("InspectionStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Inspection_Status");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<int?>("LineTotal")
                        .HasColumnType("int")
                        .HasColumnName("Line_Total");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("Manufacturing_Date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasColumnName("Quantity_Ordered");

                    b.Property<int?>("QuantityReceived")
                        .HasColumnType("int")
                        .HasColumnName("Quantity_Received");

                    b.Property<int>("ReceivingOrderId")
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Order_ID");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("Unit_Price");

                    b.HasKey("ReceivingDetailId")
                        .HasName("PK__Receivin__E574C4344D83659C");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReceivingOrderId");

                    b.ToTable("Receiving_Order_Details", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrderSerial", b =>
                {
                    b.Property<int>("ReceivingSerialId")
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Serial_ID");

                    b.Property<string>("Condition")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("Received_Date");

                    b.Property<int>("ReceivingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("Receiving_Detail_ID");

                    b.Property<int>("SerialId")
                        .HasColumnType("int")
                        .HasColumnName("Serial_ID");

                    b.HasKey("ReceivingSerialId")
                        .HasName("PK__Receivin__C3FCCEAB6061470F");

                    b.HasIndex("ReceivingDetailId");

                    b.HasIndex("SerialId");

                    b.ToTable("Receiving_Order_Serials", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.StockBalance", b =>
                {
                    b.Property<int>("StockBalanceId")
                        .HasColumnType("int")
                        .HasColumnName("Stock_Balance_ID");

                    b.Property<int?>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Available_Quantity");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("Item_ID");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("Last_Updated");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("int")
                        .HasColumnName("Reorder_Point");

                    b.Property<int?>("ReservedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Reserved_Quantity");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("Store_Id");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Total_Quantity");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("StockBalanceId")
                        .HasName("PK__Stock_Ba__A1BC83E269F6175F");

                    b.HasIndex("ItemId");

                    b.HasIndex("StoreId");

                    b.ToTable("Stock_Balance", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("Store_Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ContactNumber")
                        .HasColumnType("int")
                        .HasColumnName("Contact_Number");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("Create_Date");

                    b.Property<int?>("StorageCapacity")
                        .HasColumnType("int")
                        .HasColumnName("Storage_Capacity");

                    b.Property<int>("StoreCode")
                        .HasColumnType("int")
                        .HasColumnName("Store_Code");

                    b.Property<int?>("StoreManager")
                        .HasColumnType("int")
                        .HasColumnName("Store_Manager");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Store_Name");

                    b.Property<string>("StoreStatus")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Store_Status");

                    b.Property<string>("StoreType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Store_Type");

                    b.HasKey("StoreId")
                        .HasName("PK__Store__A0F15B611BE5CFEA");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ContactPerson")
                        .HasColumnType("int")
                        .HasColumnName("Contact_Person");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Payment_Terms");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SupplierCode")
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Code");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Supplier_Name");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__83918DB8C46E9E25");

                    b.HasIndex(new[] { "SupplierCode" }, "UQ__Supplier__1D8777D0414721B6")
                        .IsUnique();

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InvetoryManagementSystem.InventoryTransactionLog", b =>
                {
                    b.HasOne("InvetoryManagementSystem.Store", "FromStore")
                        .WithMany("InventoryTransactionLogFromStores")
                        .HasForeignKey("FromStoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__From___5BE2A6F2");

                    b.HasOne("InvetoryManagementSystem.ItemMaster", "Item")
                        .WithMany("InventoryTransactionLogs")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Item___59FA5E80");

                    b.HasOne("InvetoryManagementSystem.ItemSerialNumber", "Serial")
                        .WithMany("InventoryTransactionLogs")
                        .HasForeignKey("SerialId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Seria__5AEE82B9");

                    b.HasOne("InvetoryManagementSystem.Store", "ToStore")
                        .WithMany("InventoryTransactionLogToStores")
                        .HasForeignKey("ToStoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__To_St__5CD6CB2B");

                    b.Navigation("FromStore");

                    b.Navigation("Item");

                    b.Navigation("Serial");

                    b.Navigation("ToStore");
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrder", b =>
                {
                    b.HasOne("InvetoryManagementSystem.Store", "Store")
                        .WithMany("IssueOrders")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Issue_Ord__Store__4F7CD00D");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrderDetail", b =>
                {
                    b.HasOne("InvetoryManagementSystem.IssueOrder", "IssueOrder")
                        .WithMany("IssueOrderDetails")
                        .HasForeignKey("IssueOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Issue_Ord__Issue__52593CB8");

                    b.HasOne("InvetoryManagementSystem.ItemMaster", "Item")
                        .WithMany("IssueOrderDetails")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Issue_Ord__Item___534D60F1");

                    b.Navigation("IssueOrder");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrderSerial", b =>
                {
                    b.HasOne("InvetoryManagementSystem.IssueOrderDetail", "IssueDetail")
                        .WithMany("IssueOrderSerials")
                        .HasForeignKey("IssueDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__Issue_Ord__Issue__5629CD9C");

                    b.HasOne("InvetoryManagementSystem.ItemSerialNumber", "Serial")
                        .WithMany("IssueOrderSerials")
                        .HasForeignKey("SerialId")
                        .IsRequired()
                        .HasConstraintName("FK__Issue_Ord__Seria__571DF1D5");

                    b.Navigation("IssueDetail");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ItemSerialNumber", b =>
                {
                    b.HasOne("InvetoryManagementSystem.Store", "CurrentStore")
                        .WithMany("ItemSerialNumbers")
                        .HasForeignKey("CurrentStoreId")
                        .HasConstraintName("FK__Item_Seri__Curre__3E52440B");

                    b.HasOne("InvetoryManagementSystem.ItemMaster", "Item")
                        .WithMany("ItemSerialNumbers")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Item_Seri__Item___3D5E1FD2");

                    b.Navigation("CurrentStore");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrder", b =>
                {
                    b.HasOne("InvetoryManagementSystem.Store", "Store")
                        .WithMany("ReceivingOrders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Store__44FF419A");

                    b.HasOne("InvetoryManagementSystem.Supplier", "Supplier")
                        .WithMany("ReceivingOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Suppl__440B1D61");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrderDetail", b =>
                {
                    b.HasOne("InvetoryManagementSystem.ItemMaster", "Item")
                        .WithMany("ReceivingOrderDetails")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Item___48CFD27E");

                    b.HasOne("InvetoryManagementSystem.ReceivingOrder", "ReceivingOrder")
                        .WithMany("ReceivingOrderDetails")
                        .HasForeignKey("ReceivingOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Recei__47DBAE45");

                    b.Navigation("Item");

                    b.Navigation("ReceivingOrder");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrderSerial", b =>
                {
                    b.HasOne("InvetoryManagementSystem.ReceivingOrderDetail", "ReceivingDetail")
                        .WithMany("ReceivingOrderSerials")
                        .HasForeignKey("ReceivingDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Recei__4BAC3F29");

                    b.HasOne("InvetoryManagementSystem.ItemSerialNumber", "Serial")
                        .WithMany("ReceivingOrderSerials")
                        .HasForeignKey("SerialId")
                        .IsRequired()
                        .HasConstraintName("FK__Receiving__Seria__4CA06362");

                    b.Navigation("ReceivingDetail");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("InvetoryManagementSystem.StockBalance", b =>
                {
                    b.HasOne("InvetoryManagementSystem.ItemMaster", "Item")
                        .WithMany("StockBalances")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Stock_Bal__Item___5FB337D6");

                    b.HasOne("InvetoryManagementSystem.Store", "Store")
                        .WithMany("StockBalances")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Stock_Bal__Store__60A75C0F");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DomainLayer.Models.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DomainLayer.Models.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DomainLayer.Models.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrder", b =>
                {
                    b.Navigation("IssueOrderDetails");
                });

            modelBuilder.Entity("InvetoryManagementSystem.IssueOrderDetail", b =>
                {
                    b.Navigation("IssueOrderSerials");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ItemMaster", b =>
                {
                    b.Navigation("InventoryTransactionLogs");

                    b.Navigation("IssueOrderDetails");

                    b.Navigation("ItemSerialNumbers");

                    b.Navigation("ReceivingOrderDetails");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ItemSerialNumber", b =>
                {
                    b.Navigation("InventoryTransactionLogs");

                    b.Navigation("IssueOrderSerials");

                    b.Navigation("ReceivingOrderSerials");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrder", b =>
                {
                    b.Navigation("ReceivingOrderDetails");
                });

            modelBuilder.Entity("InvetoryManagementSystem.ReceivingOrderDetail", b =>
                {
                    b.Navigation("ReceivingOrderSerials");
                });

            modelBuilder.Entity("InvetoryManagementSystem.Store", b =>
                {
                    b.Navigation("InventoryTransactionLogFromStores");

                    b.Navigation("InventoryTransactionLogToStores");

                    b.Navigation("IssueOrders");

                    b.Navigation("ItemSerialNumbers");

                    b.Navigation("ReceivingOrders");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("InvetoryManagementSystem.Supplier", b =>
                {
                    b.Navigation("ReceivingOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
